### PR TITLE
Fixing issue #121

### PR DESCRIPTION
**Pull request by rob19780114**
Adding default location of `nvm-windows` (as found [here](https://github.com/coreybutler/nvm-windows) and linked in the official docs [here](https://github.com/creationix/nvm/blob/master/README.markdown).

### CODE REVIEW

**Comment by maxpavlov** [comment]
@jonnyzzz Could you please review, integrate and rebuild this one-liner fix? This is blocking perhaps numerous TC instances that rely on node on Windows.

**Comment by jonnyzzz** [comment]
Hardcoding OS specific paths is not a way to go. Could you please provide a PR where you are able to infer path from actual state of things. There are quite many installations of TeamCity where people not using Administrator as used account to run build agent.

**Comment by maxpavlov** [comment]
Favor https://github.com/jonnyzzz/TeamCity.Node/pull/126 over this pull request.

**Comment by rob19780114** [comment]
Already fixed through #126

**Pull request closed without merging**
