### PR TITLE
Install latest released nvm version

### PR DESCRIPTION
**Pull request by VladRassokhin**

### CODE REVIEW

**Comment by jonnyzzz** [comment]
Please rebase it on master to remove commits we merged. 
We require tests for GitHub code you've authored.

Do you select latest selected release from GitHub? If so, do you do it on every build agent? You may easily run out of GitHub API calls. Let's move this logic on the server and update builds once per day only. You may use properties provider for it. 

Every broken NVM release will lead to issues to our plugin too. Beware of it

**Comment by VladRassokhin** [comment]
>Do you select latest selected release from GitHub? If so, do you do it on every build agent?
Yes, in current implementation each agent would contact GitHub server two times a day (normally).
If all agents (>60) would communicate from single ip, they may experience problems.
Note that if api.github.com returns 304 API calls quota not changed. So matching by 'If-None-Match' and 'ETag' if it's supported by endpoint (like on our case) significantly lowers chances to run out of API calls quota.

> Let's move this logic on the server and update builds once per day only. 
Could be done, and that special parameter would be added only for builds with enabled 'NVM Install' step.

>Every broken NVM release will lead to issues to our plugin too. Beware of it
NVM url still can be specified in runner settings, but special 'use latest nvm' checkbox may be added. Or 'NVM Url' redesigned into simple version selector with 'latest' as special value.

**Comment by jonnyzzz** [comment]
Let's take it from the other angle. Do you expect your NVM build runner to fail suddenly? 
This is likely that it may fail because some update on an NVM side. Overall it makes it difficult to have stable builds because of the feature. 

What to you say is we have the following: 
 - plugin uses latest available version as form default
 - all persisted runner configurations contains an explicit version
 - we have unit tests for latest version discovery code, that is now being executed from server

I'm totally for the idea to show some sort of warning or inspections for everyone if we are using not the actual version of NVM.

**Comment by jonnyzzz** [comment]
Vlad, any plans to have this completed? It turned out we need it for some servers :)

**Pull request closed without merging**
