### PR TITLE
Added support for yarn runner

### LINKED ISSUE #116: Yarn support
Is it posible to support Yarn in a future release?

### PR DESCRIPTION
**Pull request by fkrauthan**
I started to add support for a yarn runner. This should already allow to execute a global installed yarn runner (I followed the same pattern as NPM runner works).

This is still WIP as I plan to add automatic install of yarn in case it was not successful detected.

Fixes #116

### CODE REVIEW

**Comment by fkrauthan** [comment]
Sorry yeah I missed one replace. Should be fixed now. I have a quick question for installing yarn. Do you think the goal should auto install yarn if its not available, or should I create a separate goal to install yarn (similar to nvm?)

**Comment by jonnyzzz** [comment]
Currently, NVM stuff is not working good enough. There are a number of issues to make it work slightly in the other way. Maybe it's not a good idea for now to invest into integrating yarn with NVM. 
The main failure here is that NVM re-downloads itself for every build. It is not able to check if nvm is compatible with agent. Finally, the way an agent incompatibility is solved confuses users.

Lets try to keep the runner as simply as possible. It seems to me it's on to have the runner that executes yarn from an agent if it was not specified in the config. We may consider implementing auto-install upon feedback.

**Comment by fkrauthan** [comment]
Ok in this case the runner should be finished as it should work. I will give it another try later today and remove WIP flag as for now we assume they install yarn them self.

**Comment by jonnyzzz** [comment]
Thanks! I have update TeamCity build configuration. Please see plugin binaries from this PR under tag `120`

**Comment by jonnyzzz** [comment]
Could you please check if plugin binaries form the branch works. If yes, we only need to update README.md file and we are ready to merge.

**Comment by replete** [comment]
@fkrauthan It looks like this PR is waiting on a response? Any update? We'd love to use this :D

**Comment by fkrauthan** [comment]
@replete Unfortunately I can't find the time at the moment to fully test my branch. Feel free to give it a test run on your own. From a code point of view everything should be working as expected as long as yarn is installed in a way that TeamCity runners can find it.

**Comment by replete** [comment]
That's a shame, but thanks for your work. I'm not able to test anything
here :(

**Comment by fkrauthan** [comment]
I will try getting to it within the next couple of weeks.

**Comment by fkrauthan** [comment]
Sorry for the huge delay. I am getting closer into using this plugin in our companies Teamcity instance. That way I can evaluate if it really works properly better. So please stay with me for a couple of more weeks until I get things sorted out.

**Comment by fkrauthan** [comment]
Ok I did some testing and from my end it looks all good.

**Comment by wytlytningNZ** [comment]
Any update on this?

**Comment by dzonatan** [comment]
ping @jonnyzzz

**Comment by jonnyzzz** [comment]
Merged. Please try the fresh build

**Comment by jonnyzzz** [comment]
Shall we update README.md to include the feature?

**Comment by vernak2539** [comment]
when do you think this will be released? or can we already use it? @jonnyzzz

**Comment by jonnyzzz** [comment]
I suppose it was.
Please grab fresh build here
https://teamcity.jetbrains.com/project.html?projectId=TeamCityNodePlugin


Best regards,
Eugene Petrenko

**Comment by replete** [comment]
Definitely update the README.md. 
Some people have been waiting on this repo to support yarn to move on :)

I would make a PR myself, but it would feel somewhat a farcical contribution!

**Comment by vernak2539** [comment]
How exactly does this work? I would've thought it was simple as updating the plugin on the server and having the server push down the agent files, but it didn't look like it.

We've updated the server plugin and the agent files have been updated via the server as well. We can select the npm yarn task as a build step, but then none of the agents are compatible. We get the message...

```
Unmet requirements: 
node.js.yarn exists
```

I can see the files on the server and the agent. Agent files were updated today. I guess I'm a little lost. Is there anything else that I'm missing?

**Comment by fkrauthan** [comment]
Yes you need to manual install yarn on your agents

**Comment by vernak2539** [comment]
@fkrauthan ahhhhh okay. will give that a try

**Comment by vernak2539** [comment]
@fkrauthan thank you! that worked like a charm

**Comment by fkrauthan** [comment]
@Nelrohd take a look at the yarn website: https://yarnpkg.com/lang/en/docs/install/#linux-tab

**Comment by Nelrohd** [comment]
@fkrauthan thank you! I had to restart team city to make it work after.

**Pull request merged**
